### ISSUE TITLE
Crashes in Catalina 10.15.2 (19C57) 

### ISSUE THREAD

**Issue by msp** [kfix/MacPin#34]
I tried opening the built in Trello and Google Drive apps:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MacPin.MPWebView _drawsTransparentBackground]: unrecognized selector sent to instance 0x7f8857528520'
abort() called
terminating with uncaught exception of type NSException

**Comment by kfix** [comment]
I think I've had the same happen. I've since added some runtime versioning smarts to gate calls to these private methods of WebKit but sometimes the wrong bits get flipped :-/

without knowing what version/build you were working from, don't really have a clue what to do with this except asking to try again with a newer build + OS.

**Comment by msp** [comment]
From distant memory I think I evaluated and bailed when it didn't work so I don't have a running version or any more diagnostic info I'm afraid! Feel free to close :)

**Comment by kfix** [comment]
giving up on catalina, sorry folks!
